export {default as Navbar } from './Navbar/Navbar'
export {default as Slider } from './Slider/Slider'
export {default as Card } from './Card/Card'
export { default as Info } from './Info/Info'
export {default as Form } from './Form/Form'
export {default as Footer } from './Footer/Footer'
export { default as Vision } from './Vision/Vision'
export { default as Table } from './Table/Table'
// export { default as Samples } from './Samples/Samples'
export { default as Handy } from './Handy/Handy'
export { default as Heading } from './Heading/Heading'
export { default as Video } from './Video/Video'
export { default as Map } from './Map/Map'
export { default as WhatsApp } from './WhatsApp/WhatsApp'
export { default as ProductButton } from './ProductButton/ProductButton'
export { default as Brands } from './Brands/Brands'
